// <auto-generated/>
// Generated by QueryGenerator.Generate_old. Do not edit manually.
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Collections.Generic;

namespace GeneratedQueries
{
    public static partial class ReportingPeriodQuery
    {
        /// <summary>
        /// Auto-generated from HQL named query "ALL"
        /// HQL: SELECT * FROM am_reportperiod
        /// </summary>
        public static Expression<Func<global::eportingPeriod, bool>> ALL()
        {
            return x => true; // no WHERE
        }

        /// <summary>
        /// Auto-generated from HQL named query "FindAllMonthlyOrQuarterly"
        /// HQL: from ReportingPeriod period where (Type.Id = 'M' or Type.Id = 'Q') and EndDate = ?
        /// </summary>
        public static Expression<Func<global::ReportingPeriod, bool>> FindAllMonthlyOrQuarterly(object p1)
        {
            return x => (Type.Id = 'M' or Type.Id = 'Q') and EndDate = p1;
        }

        
        public const string FindRollForwardPeriodsSql = @"
		SELECT *
		FROM AM_ReportPeriod r
		JOIN AM_RollForwardReportingStatus s
		ON r.ReportPeriod_GUID = s.ReportPeriodTo_GUID
		WHERE r.ReportPeriodType_Code = 'M'
		AND s.RollForwardType_Code = 'HRCY'
		ORDER BY r.ReportPeriodEndDate DESC
	";

        /// <summary>
        /// Auto-generated from SQL named query "FindThirdPartyReviewPeriods".
        /// </summary>
        public const string FindThirdPartyReviewPeriodsSql = @"
    select *
    from AM_ReportPeriod rp
    where rp.ReportPeriod_GUID in (
      select distinct tpr.period_guid
      FROM AM_ThirdPartyAssetReview tpr
    )
  ";

       
}
